version: "2.1"

services:
  # Enable docker to auto-run any architecture image using qemu
  #     docker run --rm --privileged multiarch/qemu-user-static:register --reset
  multiarch:
    container_name: multiarch
    image: multiarch/qemu-user-static:register
    privileged: true
    restart: "no"

  tor:
    build: .
    image: sofwerx/tor:arm-static
    volumes:
      - ./outputs/:/outputs/
    depends_on:
      - multiarch
    command: cp -r install/bin/tor /outputs/ 
